name: Flask Docker Test

on:
  push:
    paths:
      - 'python-app/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Test Flask App
        run: |
          cd python-app
          docker build -t flask-hello .

          docker run -d -p 8080:8080 --name flask-test flask-hello
          sleep 8

          echo "Testing the app..."
          curl -f --retry 10 --retry-delay 1 http://localhost:8080 || exit 1

          echo "Container logs:"
          docker logs flask-test

      - name: Cleanup
        if: always()
        run: |
          docker stop flask-test || true
          docker rm flask-test || true
